### ISSUE TITLE
Add loading indicator to sharing page

### ISSUE THREAD

**Issue by nathanlim1** [nathanlim1/WrappedOnDemand#84]
Currently, sharing links taking app users to the sharing page go to the page instantly, but it takes up to 11 seconds for the actual shared data to load onto the page. There is not much we can do about this loading time other than modifying the routes, but even if we get the loading time to 1 second, it is best to display a loading indicator to the users so that they know that the data is being loaded and the page is not just blank.

est time - 1 hr

**Comment by logancostello** [comment]
Actual: 20 mins
